# Generated by Django 5.2.7 on 2025-11-06 08:42

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_gallerysection_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.TeamMember.team_photo_upload_path),
        ),
    ]
