# Generated by Django 5.2.7 on 2025-11-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teammember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('nonbinary', 'Non-binary'), ('other', 'Other')], max_length=16),
        ),
    ]
